#!/bin/bash
# Script to help get Firebase service account key for GitHub Actions

echo "🔑 Getting Firebase Service Account Key"
echo "========================================"
echo ""
echo "Due to organization policies, we need to get the key from Firebase Console."
echo ""
echo "Follow these steps:"
echo ""
echo "1. Open this URL in your browser:"
echo "   https://console.firebase.google.com/project/kindlyroe-website/settings/serviceaccounts/adminsdk"
echo ""
echo "2. Click 'Generate new private key'"
echo ""
echo "3. Click 'Generate key' in the confirmation dialog"
echo ""
echo "4. The JSON file will download automatically"
echo ""
echo "5. Run this command to add it to GitHub:"
echo "   gh secret set FIREBASE_SERVICE_ACCOUNT_KINDLYROE_WEBSITE --body \"\$(cat path/to/downloaded/key.json)\""
echo ""
echo "Or if you want to paste it manually:"
echo "   gh secret set FIREBASE_SERVICE_ACCOUNT_KINDLYROE_WEBSITE"
echo ""
echo "The service account email to use:"
echo "   firebase-adminsdk-fbsvc@kindlyroe-website.iam.gserviceaccount.com"
echo ""

