name: Deploy to Firebase (Workload Identity)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for Workload Identity Federation

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/108074550869/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: ci-deployer@kindlyroe-website.iam.gserviceaccount.com

      - name: Install dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set Firebase project
        run: firebase use kindlyroe-website

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting,functions
